name: EBAC CI

on:
    push:
        branches: [ci]

    workflow_dispatch:
permissions:
    contents: write
jobs:
    test:
        runs-on: ubutu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2

              with:
                  node-version: 16
            - name: npm test
              uses: cypress-io/github-action@v5
              continue-on-error: true
              with:
                  install-command: npm install
                  start: npm start
